### ISSUE TITLE
Doesn't work with a `gulp.src` array

### ISSUE THREAD

**Issue by karlhorky** [wmluke/gulp-inline-angular-templates#3]
When the parameter passed to `gulp.src` is an array, the plugin errors out.

``` js
var paths = [
  './**/*.html',
  './!(templates.html)',
  './!(bower_components|node_modules)/**/*.html'
];

gulp.task('html', function() {
  gulp.src(paths)
    .pipe(inlineAngularTemplates('templates.html', {
      selector: 'span'
    }));
});
```

It fails with the following error:

``` shell
[14:16:53] Starting 'html'...
[14:16:53] Finished 'html' after 4.39 ms

/Users/karlhorky/Projects/app/node_modules/gulp-inline-angular-templates/src/index.js:39
            return cb();
                   ^
ReferenceError: cb is not defined
    at Stream.transform (/Users/karlhorky/Projects/app/node_modules/gulp-inline-angular-templates/src/index.js:39:20)
    at Stream.stream.write (/Users/karlhorky/Projects/app/node_modules/gulp-inline-angular-templates/node_modules/event-stream/node_modules/through/index.js:26:11)
    at write (/Users/karlhorky/Projects/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/karlhorky/Projects/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/karlhorky/Projects/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:92:17)
    at emitReadable_ (/Users/karlhorky/Projects/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/karlhorky/Projects/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/karlhorky/Projects/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/karlhorky/Projects/app/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
```

**Comment by karlhorky** [comment]
A workaround is to do all of your negations in one string, but this is not pretty:

``` js
gulp.src('./!(bower_components|node_modules)/**/!(templates).html')
  .pipe(inlineAngularTemplates('templates.html', {})
  .pipe(gulp.dest('.'));
```
